#' Generate simulated time-to-event data
#'
#' Simulation of time-to-event (tte) data.
#'
#' After specification of the input, the data simulation works as follows:
#'
#' The absolute number of cases due to background causes (other than the adr) is
#' generated by the binomial distribution with \code{prob = br}.
#' The absolute number of cases due to the medication is generated by the
#' binomial distribution with \code{prob = br*adr}. All in all, the expected
#' number of events/cases within the data set is
#' \eqn{n \cdot br (1 + adr)}.
#'
#' The event-times can have values between zero and censor. Time point zero is the date of
#' the medication (or start of regular medication) and the censor is the
#' official end time of the cohort study.
#'
#' For the br cases, the event-times are generated using a uniform distribution on
#' the interval \eqn{[0,} \code{censor} \eqn{]}. For the adr cases, event-times follow a normal
#' distribution. The mean of the normal distribution is at either 0.25, 0.5 or 0.75 times
#' censor. The standard deviation is defined as
#' \eqn{ rel.sd \cdot censor}. All generated event-times
#' \eqn{\leq 0} are set to 1.
#'
#' @param genpar A vector containing 6 elements, namely:
#' \enumerate{
#'       \item the sample size N,
#'       \item the background rate br (observed in population on average),
#'       \item the adverse drug reaction rate as proportion of the background rate,
#'       \item the ADR mean time quantile percentage based on the length of the
#'             observation period,
#'       \item the ADR relative standard deviation from the mean time relative to
#'             the observation period length
#'       \item the study end time point and censoring time for all subjects without
#'             event up to that point.
#'             }
#'
#' @return A simulated time-to-event data frame of size N
#' 
#' @examples
#' sim.datagen_tte(c(100, 0.1, 1, 0.5, 0.05, 365))
#' 
#' @export



sim.datagen_tte = function(genpar){
  genpar = as.numeric(genpar)
  n = genpar[1]
  br = genpar[2]
  adr.rate = genpar[3]
  adr.quantile = genpar[4]
  adr.relsd = genpar[5]
  censor = genpar[6]

  # Number of br & adr cases in the study
  n.br = stats::rbinom(1,n, prob = br)
  n.adr = stats::rbinom(1,n, prob = br*adr.rate)
  # event time for background event candidates
  t.br = stats::runif(n.br, min = 0, max = censor)

  # mean time point for adr events
  m.adr = round(adr.quantile*censor)
  # standard deviation for adr event times
  sd.adr = adr.relsd*censor
  # event time for adr event candidates
  t.adr = stats::rnorm(n.adr, mean = m.adr, sd = sd.adr)
  # adjustment for negative time points
  if(sum(t.adr<=0)>0){
    t.adr[t.adr<=0] = 1
  }
  # number of events in the observation period
  n.events = length(c(t.br, t.adr))
  # status vector for whole sample
  status = c(rep(1,n.events), rep(0, n-n.events))
  # time vector (continuous values) for whole sample
  time = c(t.br, t.adr, rep(censor,n-n.events))
  # time vector (daily scale) for whole sample
  time = ceiling(time)
  dat = data.frame(time, status)

  return(data = dat)
}
